
#!/usr/bin/env python3
"""
fas2gdb.py - Convert FASM .fas debug symbols to GDB script
Filters only valid user-defined labels (clean ASCII identifiers)
"""
import struct, sys, os, re
from collections import Counter

FAS_SIGNATURE = 0x1A736166

def read_dword(data, offset): return struct.unpack_from('<I', data, offset)[0]
def read_qword(data, offset): return struct.unpack_from('<Q', data, offset)[0]
def read_word(data, offset):  return struct.unpack_from('<H', data, offset)[0]

def read_cstring(data, offset):
    end = data.index(0, offset)
    return data[offset:end].decode('latin-1')

def read_pascal_string(data, offset):
    length = data[offset]
    return data[offset+1:offset+1+length].decode('latin-1')

# Допустимые имена меток: начинаются с буквы или точки, только [A-Za-z0-9_.]
VALID_NAME = re.compile(r'^[A-Za-z_.][A-Za-z0-9_.]*$')

def is_valid_label(name):
    if not VALID_NAME.match(name):
        return False
    if len(name) < 2 or len(name) > 64:
        return False
    # Исключить имена похожие на инструкции
    asm_keywords = {'mov','add','sub','jmp','jz','jnz','je','call','ret',
                    'push','pop','xor','and','or','cmp','inc','dec','nop',
                    'int','iret','sti','cli','hlt','equ','db','dw','dd'}
    if name.lower() in asm_keywords:
        return False
    return True

def parse_fas(filename):
    with open(filename, 'rb') as f:
        data = f.read()

    sig = read_dword(data, 0)
    if sig != FAS_SIGNATURE:
        print(f"ERROR: Not a .fas file", file=sys.stderr)
        sys.exit(1)

    header_len     = read_word(data, 6)
    strings_offset = read_dword(data, 16)
    strings_length = read_dword(data, 20)
    symbols_offset = read_dword(data, 24)
    symbols_length = read_dword(data, 28)
    source_offset  = read_dword(data, 32)

    strings_data = data[strings_offset:strings_offset + strings_length]

    ENTRY = 32
    raw_symbols = []
    i = 0
    while i + ENTRY <= symbols_length:
        base   = symbols_offset + i
        value  = read_qword(data, base + 0)
        flags  = read_word(data,  base + 8)
        name_f = read_dword(data, base + 24)

        defined     = bool(flags & 0x1)
        is_variable = bool(flags & 0x2)

        if defined and not is_variable and name_f != 0:
            name = None
            try:
                if name_f & 0x80000000:
                    str_off = name_f & 0x7FFFFFFF
                    if str_off < len(strings_data):
                        name = read_cstring(strings_data, str_off)
                else:
                    src_off = source_offset + name_f
                    if src_off < len(data):
                        name = read_pascal_string(data, src_off)
            except Exception:
                pass

            if name and is_valid_label(name):
                raw_symbols.append((name, value))

        i += ENTRY

    # Убрать адреса которые повторяются слишком много раз (константы/мусор)
    addr_count = Counter(addr for _, addr in raw_symbols)
    symbols = [(n, a) for n, a in raw_symbols if addr_count[a] <= 3 and a > 0]

    # Убрать дубликаты (одно имя → один адрес)
    seen_names = set()
    unique = []
    for name, addr in sorted(symbols, key=lambda x: x[1]):
        if name not in seen_names:
            seen_names.add(name)
            unique.append((name, addr))

    return unique

def main():
    if len(sys.argv) < 2:
        print(f"Usage: {sys.argv[0]} input.fas [output.gdb]")
        sys.exit(1)

    fas_file = sys.argv[1]
    gdb_file = sys.argv[2] if len(sys.argv) > 2 else os.path.splitext(fas_file)[0] + ".gdb"

    symbols = parse_fas(fas_file)

    with open(gdb_file, 'w') as f:
        f.write("# Auto-generated by fas2gdb.py\n")
        f.write("set disassembly-flavor intel\n\n")
        for name, addr in symbols:
            gdb_name = name.replace(".", "_")
            f.write(f"set ${gdb_name} = 0x{addr:x}\n")
        f.write("\necho [fas2gdb] Symbols loaded.\\n\n")

    print(f"[fas2gdb] {len(symbols)} symbols -> {gdb_file}", file=sys.stderr)
    for name, addr in symbols:
        gdb_name = name.replace(".", "_")
        print(f"  0x{addr:016x}  {gdb_name}")

if __name__ == "__main__":
    main()

